/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.trvedata.sgm.communication;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum AccountableDcgkaMessageType implements org.apache.thrift.TEnum {
  CREATE(0),
  UPDATE(1),
  REMOVE(2),
  ADD(3),
  WELCOME(4),
  ACK(5),
  ACK_WITH_UPDATE(6),
  ADD_ACK(7),
  REVEAL(8);

  private final int value;

  private AccountableDcgkaMessageType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static AccountableDcgkaMessageType findByValue(int value) { 
    switch (value) {
      case 0:
        return CREATE;
      case 1:
        return UPDATE;
      case 2:
        return REMOVE;
      case 3:
        return ADD;
      case 4:
        return WELCOME;
      case 5:
        return ACK;
      case 6:
        return ACK_WITH_UPDATE;
      case 7:
        return ADD_ACK;
      case 8:
        return REVEAL;
      default:
        return null;
    }
  }
}
